markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme
  - jekyll-sitemap

re:
  favicon: https://raw.githubusercontent.com/klaudiosinani/klaudiosinani.github.io/refs/heads/master/public/favicon.png

defaults:
  - 
    scope:
      path: "README.md"
    values:
      permalink: "/"
      layout: "default"
  -
    scope:
      path: "readme.md" 
    values:
      permalink: "/"
      layout: "default"