markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

defaults:
  - 
    scope:
      path: "README.md"
    values:
      permalink: "/"
      layout: "default"
  -
    scope:
      path: "readme.md" 
    values:
      permalink: "/"
      layout: "default"